version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: fastapi dev ./src/main.py --port 80 --host 0.0.0.0
    volumes:
      - .:/src
    ports:
      - "9010:80"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  test_db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}

    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
